[package]
name = "roomci-serve"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
roomci-core = { path = "../roomci-core" }
roomci-device-model = { path = "../roomci-device-model" }
roomci-report = { path = "../roomci-report" }
roomci-scenario = { path = "../roomci-scenario" }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
