[package]
name = "roomci-device-model"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"
publish.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
