[package]
name = "roomci-ops"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
serde_yaml.workspace = true
thiserror.workspace = true
