[package]
name = "roomci-core"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"
publish.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
chrono.workspace = true
roomci-device-model = { path = "../roomci-device-model" }
roomci-edge = { path = "../roomci-edge" }
roomci-mqtt = { path = "../roomci-mqtt" }
roomci-ops = { path = "../roomci-ops" }
roomci-scenario = { path = "../roomci-scenario" }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
