[package]
name = "roomci-cli"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"
publish.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "roomci"
path = "src/main.rs"

[dependencies]
clap.workspace = true
chrono.workspace = true
mio = { version = "1.2.3", features = ["net", "os-poll"] }
roomci-core = { path = "../roomci-core" }
roomci-report = { path = "../roomci-report" }
roomci-scenario = { path = "../roomci-scenario" }
roomci-serve = { path = "../roomci-serve" }
same-file.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
rumqttc = { version = "0.25.1", default-features = false }

[dev-dependencies]
tempfile.workspace = true
